package simpledb.storage;

import simpledb.transaction.TransactionId;

/**
 * Page is the interface used to represent pages that are resident in the
 * BufferPool.  Typically, DbFiles will read and write pages from disk.
 * DbFile会从磁盘中读取和写入Page
 * <p>
 * Pages may be "dirty", indicating that they have been modified since they
 * were last written out to disk.
 * 页可能变为“脏”状态，这表明他们在上一次被写入磁盘后又被修改过
 * <p>
 * For recovery purposes, pages MUST have a single constructor of the form:
 * Page(PageId id, byte[] data)
 */
public interface Page {

    /**
     * Return the id of this page.  The id is a unique identifier for a page
     * that can be used to look up the page on disk or determine if the page
     * is resident in the buffer pool.
     * PageId是Page的唯一标识
     *
     * @return the id of this page
     */
    PageId getId();

    /**
     * Get the id of the transaction that last dirtied this page, or null if the page is clean.
     * 获取使页处于“脏”状态的事务id，如果不处于“脏”状态则返回null
     *
     * @return The id of the transaction that last dirtied this page, or null
     */
    TransactionId isDirty();

    /**
     * Set the dirty state of this page as dirtied by a particular transaction
     */
    void markDirty(boolean dirty, TransactionId tid);

    /**
     * Generates a byte array representing the contents of this page.
     * Used to serialize this page to disk.
     * 将页中的内容转换为字节数组并序列化到磁盘里
     * <p>
     * The invariant here is that it should be possible to pass the byte array
     * generated by getPageData to the Page constructor and have it produce
     * an identical Page object.
     * 这里的不变量是可以将 getPageData 生成的字节数组传递给 Page 构造函数并让它生成一个相同的 Page 对象
     *
     * @return A byte array correspond to the bytes of this page.
     */

    byte[] getPageData();

    /**
     * Provide a representation of this page before any modifications were made
     * to it.  Used by recovery.
     * 在对其进行任何修改之前提供此页面的表示。 用于恢复。
     */
    Page getBeforeImage();

    /*
     * a transaction that wrote this page just committed it.
     * copy current content to the before image.
     * 在事务提交修改当前页面前， 将当前内容复制到之前的图像。
     */
    void setBeforeImage();
}
